on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:
jobs:
  check-meta-riscv:
    runs-on: tgamblin-maintenance
    container:
      image: ${{ vars.BOARDGARDEN_HOST }}/${{ vars.BOARDGARDEN_OWNER }}/yocto-builder
    steps:
      - name: run yocto-check-layer-wrapper
        run: |
          locale-gen en_US.UTF-8
          export LANG=en_US.UTF-8
          git clone "${GITHUB_SERVER_URL}/${{ vars.BOARDGARDEN_OWNER }}/boardgarden.git" .
          git clone "${GITHUB_SERVER_URL}/${{ vars.BOARDGARDEN_OWNER }}/openembedded-core.git"
          git clone "${GITHUB_SERVER_URL}/${{ vars.BOARDGARDEN_OWNER }}/bitbake.git" openembedded-core/bitbake
          git clone "${GITHUB_SERVER_URL}/${{ vars.BOARDGARDEN_OWNER }}/meta-riscv.git"
          cd openembedded-core && source oe-init-build-env
          bitbake-layers add-layer ../../meta-riscv
          echo "DL_DIR = \"/buildcache/downloads\"" >> conf/local.conf
          echo "SSTATE_DIR = \"/buildcache/sstate-cache\"" >> conf/local.conf
          yocto-check-layer-wrapper ../../meta-riscv
