---
- name: Install podman
  ansible.builtin.apt:
    name: podman
    state: present
    update_cache: true

- name: Deploy testresults file server
  ansible.builtin.import_tasks: testresults.yml

- name: Deploy tftpd-hpa
  ansible.builtin.import_tasks: tftpd-hpa.yml
